#pragma once

enum spriteType {
	sprite_type_unknown,
	sprite_type_block_1x1,
	sprite_type_brick_1x1,
	sprite_type_bricksecretbox_1x1,
	sprite_type_brick_fragment,
	sprite_type_bushes_3x1,
	sprite_type_bushes_4x1,
	sprite_type_bushes_5x1,
	sprite_type_castle_5x5,
	sprite_type_cloud_3x2,
	sprite_type_cloud_4x2,
	sprite_type_cloud_5x2,
	sprite_type_flag_2x1,
	sprite_type_flagpole_1x9,
	sprite_type_floor_1x1,
	sprite_type_flower_1x1,
	sprite_type_goldcoin_1x1,
	sprite_type_goombas_1x1,
	sprite_type_greenball_1x1,
	sprite_type_hill_3x2,
	sprite_type_hill_5x3,
	sprite_type_itemselector,
	sprite_type_mario,
	sprite_type_mushroom_1x1,
	sprite_type_secretbox_1x1,
	sprite_type_passblock_1x1,
	sprite_type_tortoise_1x1,
	sprite_type_tube_2x2,
	sprite_type_tube_2x3,
	sprite_type_tube_2x4,
};